filter:
    excluded_paths:
        - "tests/*"
        - "features/*"
        - "vendor/*"

tools:
    external_code_coverage:
        timeout: 600

    php_sim: true

    php_changetracking: true

    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            excluded_paths:
                - "tests/*"
                - "features/*"
                - "vendor/*"

    php_mess_detector:
        enabled: true
        filter:
            excluded_paths:
                - "tests/*"
                - "features/*"
                - "vendor/*"

    php_pdepend:
        enabled: true
        filter:
            excluded_paths:
                - "tests/*"
                - "features/*"
                - "vendor/*"

    php_analyzer:
        enabled: true
        filter:
            excluded_paths:
                - "tests/*"
                - "features/*"
                - "vendor/*"


    php_cpd:
        enabled: true
        excluded_dirs:
            - "tests/*"
            - "features/*"
            - "vendor/*"

    php_loc:
        enabled: true
        excluded_dirs:
            - "tests/*"
            - "features/*"
            - "vendor/*"