language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
  - composer install --prefer-source
  - composer global require 'kherge/box=~2.4' --prefer-source
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - php vendor/atoum/atoum/scripts/coverage.php --format xml --output clover.xml
  - ~/.composer/vendor/bin/box build
  - vendor/bin/behat --format=progress

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
